language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: pypy3.5
      env: TOXENV=pypy

    - python: "3.7-dev"
      env: TOXENV=flake8
install:
  - pip install tox
script:
  - tox
